version: "2"

services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "tapendium/tap-build-artifact"]
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester:v3.0.1
    volumes:
      - ".:/plugin:ro"

  format:
    image: mvdan/shfmt
    volumes:
      - '.:/data'
    command:
      - --write
      - ./data
