name: tap-build-artifact-buildkite-plugin
description: Tap build artifact buildkite plugin
author: https://tapendium.com
requirements:
  - docker
configuration:
  properties:
    artifacts-path-env:
      type: string
    artifacts-path:
      type: string
    repo:
      type: string
    type:
      type: string
      enum: ["download", "upload"]
    ignore-missing:
      type: boolean
    debug:
      type: boolean
  required:
    - type
  additionalProperties: false

