#!/bin/bash

set -eo pipefail

CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="BUILDKITE_PLUGIN_TAP_BUILD_ARTIFACT_"
DEBUG_FLAG="${PREFIX}DEBUG"

# shellcheck source=lib/shared.sh
. "$CWD/../lib/shared.sh"

if [[ "${!DEBUG_FLAG:-false}" =~ (true|on|1) ]] ; then
  echo "~~~ :hammer: Enabling debug mode"
  set -x
fi

RUN_TYPE=download
REPO=${BUILDKITE_REPO:-$(plugin_read_config REPO)} 
TYPE=$(plugin_read_config TYPE)
ARTIFACTS_PATH_ENV=$(plugin_read_config ARTIFACTS_PATH_ENV)

if [ "$TYPE" != "$RUN_TYPE" ]
then
  echo "[INFO] type not equal $RUN_TYPE"
  exit 0
fi

IS_VALID=true

if [ -z "$REPO" ]
then
  echo "[ERROR] repo not defined"
  IS_VALID=false
fi

if [ -z "$ARTIFACTS_PATH_ENV" ]
then
  echo "[ERROR] artifacts-path-env not defined"
  IS_VALID=false
fi

if [[ ${IS_VALID:-true} =~ (false) ]]; then
  exit 1
fi

HEAD_COMMIT=$(git rev-parse HEAD)
COMMIT_HASH=$(curl \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  https://api.github.com/repos/"${BUILDKITE_ORGANIZATION_SLUG}"/"${REPO}"/commits/"${HEAD_COMMIT}"/pulls |
  jq -r '.[0].head.sha')

BUILD_ID=$(buildkite_metadata_get "TAP_BUILD_$COMMIT_HASH")
buildkite_artifact_download "${!ARTIFACTS_PATH_ENV}" '.' --build "$BUILD_ID"
